In [40]:
import numpy as np
dataset = np.random.randint(10,50,(5,10))
print(dataset)

[[13 35 18 40 36 45 46 27 27 32]
 [17 17 39 38 24 23 24 44 49 26]
 [33 48 33 37 30 25 35 40 33 46]
 [35 33 30 48 28 19 35 32 10 27]
 [41 38 14 38 18 20 34 42 42 24]]


In [41]:
avg = (np.sum(dataset,axis =1))/10
avg = [round(a,1) for a in avg]
print("Average points per game:")
print(avg)
sums = np.sum(dataset,axis=1)
print()
print(f"Best-performing player: Player {np.where(sums==max(sums))[0][0]} (Total: {max(sums)} points)")
print(f"Worst-performing player: Player {np.where(sums==min(sums))[0][0]} (Total: {min(sums)} points)")
print()
print("Games with scores above 30")
for i in range(len(dataset)):
    mask = dataset[i]>30
    if len(dataset[i][mask]) != 0:
        print(f"Player {i+1}: Games {dataset[i][mask]}")
print()
temp = {}
for i in range(len(sums)):
    temp[i+1] = sums[i]
# print(temp)
di = dict(sorted(temp.items(), key=lambda item: item[1],reverse = True))
i =1
print("Sorted Players by Total Points")
for j in di.keys():
    print(f"{i}. Player {j} - {di[j]} points")
    i+=1


Average points per game:
[31.9, 30.1, 36.0, 29.7, 31.1]

Best-performing player: Player 2 (Total: 360 points)
Worst-performing player: Player 3 (Total: 297 points)

Games with scores above 30
Player 1: Games [35 40 36 45 46 32]
Player 2: Games [39 38 44 49]
Player 3: Games [33 48 33 37 35 40 33 46]
Player 4: Games [35 33 48 35 32]
Player 5: Games [41 38 38 34 42 42]

Sorted Players by Total Points
1. Player 3 - 360 points
2. Player 1 - 319 points
3. Player 5 - 311 points
4. Player 2 - 301 points
5. Player 4 - 297 points
