In [1]:
!pip install numpy

In [28]:
import numpy as np

arr = np.array([2,4,5,])
arr2 = np.array([[3,4],[4,6]])
zeros = np.ones((3,3))
arr3 = np.zeros((3,3))
arr4 = np.arange(1,9,2)
arr5 = np.linspace(1,10,20)
arr6 = np.random.rand(4,4)
arr7 = np.random.randint(1,10,(4,4))
print(arr)
print(arr2)
print(arr2+10)
print(zeros)
print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(arr7)
print(arr2.shape)
                

[2 4 5]
[[3 4]
 [4 6]]
[[13 14]
 [14 16]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 3 5 7]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[0.74239282 0.34271683 0.52819828 0.30634313]
 [0.28800207 0.74797393 0.58997283 0.77338058]
 [0.71334902 0.21925876 0.77523441 0.54472835]
 [0.7498044  0.28108699 0.87175675 0.3295678 ]]
[[4 9 2 1]
 [2 5 7 1]
 [1 5 4 5]
 [5 7 2 7]]
(2, 2)


In [29]:
array2d = np.random.randint(1,50,(3,4))
print(array2d)
print(array2d[2,:])

[[ 6 13 24 48]
 [24 47 33  8]
 [10 34  8 11]]
[10 34  8 11]


In [33]:
array2d = np.random.randint(1,50,(3,4))
array2d2 = np.random.randint(1,50,(3,4))
print(array2d + array2d2)


[[55 56 58 82]
 [63 62 25  5]
 [42 87 34 33]]


In [34]:
array2d = np.random.randint(1,50,(3,4))
array2d2 = np.random.randint(1,50,(4,4))

print(np.dot(array2d,array2d2))

[[2615 3136 2310 3805]
 [ 594 1651 1541 2674]
 [ 510 1434 1092 2331]]


In [38]:
array2d = np.random.randint(1,5,(3,4))
# array2d2 = np.random.randint(1,50,(3,4))
print(array2d)
print(np.sum(array2d,axis = 1)) #0 = columns sum -- 2 for rows sum

[[2 3 4 2]
 [3 1 1 4]
 [3 3 1 4]]
[11  9 11]


In [40]:
arr = np.arange(0,12)
arr_mod = arr.reshape(3,4)
print(arr)
print(arr_mod)
print(arr_mod.T)#transpose

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [45]:
arr = np.arange(0,12)
arr1 = np.arange(0,12)
print(np.split(arr,3))
mask = arr>2
print(arr[mask])
print(np.vstack((arr,arr1)))
print(np.hstack((arr,arr1)))

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[ 3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11]


In [50]:
arr = np.arange(0,16)
print(arr.reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [51]:
!pip install pandas

In [75]:
import pandas as pd
s = pd.Series([23,54,23],index = ['a','b','c'])
# print(s)
print(s.info())
# print(s.describe())
print(s.shape)

<class 'pandas.core.series.Series'>
Index: 3 entries, a to c
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 48.0+ bytes
None
(3,)


In [79]:
data = {
    "name":["pavan","kumar"],
    "place":[3,4],
}

df = pd.DataFrame(data)
# print(df)
# for i,j in df.iterrows():
    # print(j)
df.to_csv("demo.csv",index = False)

In [80]:
d1 = pd.read_csv("demo.csv")
print(d1)

    name  place
0  pavan      3
1  kumar      4
