In [3]:
import numpy as np
dataset = np.random.randint(100,500,(30,5))
print(dataset)

[[251 160 297 396 312]
 [223 429 273 149 233]
 [291 119 239 363 469]
 [264 186 244 376 399]
 [324 408 450 134 113]
 [314 272 284 417 150]
 [363 321 471 121 159]
 [369 174 262 122 212]
 [176 273 385 387 362]
 [388 320 460 192 296]
 [235 449 388 467 260]
 [474 125 490 350 281]
 [289 340 158 366 242]
 [164 126 179 147 492]
 [323 326 303 405 175]
 [223 431 110 471 257]
 [347 342 349 154 492]
 [469 310 269 174 174]
 [143 487 420 149 257]
 [133 223 282 370 493]
 [105 456 279 100 425]
 [272 476 362 235 425]
 [275 448 243 219 288]
 [404 392 147 234 499]
 [126 445 157 401 424]
 [447 450 480 152 333]
 [154 499 246 403 396]
 [463 139 327 401 314]
 [271 167 440 370 496]
 [419 459 367 161 389]]


In [4]:
avg = (np.sum(dataset,axis =0))/30
avg = [round(a,1) for a in avg]
print("Average stock prices :",avg)
# print("Average stock prices :",dataset.mean())
maxi = np.max(dataset)
index = np.argwhere(dataset==maxi)
# print(index)
print(f"Highest price recorded: {maxi} at Day {index[0][0]+1}, Company {index[0][1]}")
norm = np.linalg.norm(dataset)
matrix = dataset/norm
print("Normalized Prices : ")
print(matrix)
print("Risky Investments Days:")
for i in range(len(dataset)):
    mask = dataset[i] <200
    if len(dataset[i][mask]) !=0:
        print(f"Day {i+1} : {dataset[i][mask]}")

Average stock prices : [290.0, 325.1, 312.0, 279.5, 327.2]
Highest price recorded: 499 at Day 24, Company 4
Normalized Prices : 
[[0.06239888 0.03977618 0.07383453 0.09844604 0.07756355]
 [0.05543805 0.10664988 0.06786811 0.03704157 0.05792406]
 [0.07234293 0.02958353 0.05941567 0.09024221 0.11659392]
 [0.0656307  0.04623981 0.06065867 0.09347402 0.09919185]
 [0.08054676 0.10142926 0.1118705  0.03331255 0.02809193]
 [0.07806075 0.0676195  0.07060272 0.10366667 0.03729017]
 [0.09024221 0.07980096 0.11709113 0.03008074 0.03952758]
 [0.09173381 0.04325659 0.06513349 0.03032934 0.05270344]
 [0.0437538  0.06786811 0.09571143 0.09620863 0.0899936 ]
 [0.09645723 0.07955236 0.11435651 0.04773141 0.07358593]
 [0.05842126 0.1116219  0.09645723 0.11609672 0.06463629]
 [0.11783693 0.03107514 0.12181455 0.08701039 0.06985691]
 [0.07184572 0.08452438 0.03927898 0.09098801 0.06016147]
 [0.04077058 0.03132374 0.0444996  0.03654436 0.12231175]
 [0.08029816 0.08104396 0.07532614 0.10068345 0.0435052 ]
 